# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Libro Modelado de Sistemas Bajo Incertidumbre - IIND 2504
author: Equipo Modelado Bajo Incertidumbre | Uniandes
logo: uniandes.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  kernel_name: libromobi

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/modelos-inst/LibroMoBI  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  extra_css:
    - _static/custom.css


parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence

sphinx:
  config:
    nb_render_markdown_format: myst
    myst_dmath_double_inline: true
    myst_update_mathjax: false
    mathjax3_config:
      options:
        processHtmlClass: "tex2jax_process|mathjax_process|math|output_area|tex2jax_ignore|mathjax_ignore"



launch_buttons:
  thebe: false



